@startuml
skinparam monochrome true
skinparam componentStyle uml2
skinparam padding 4

actor "User" as user
node "Apple Device\l(e.g. iPhone)" as apple_device #white {
  [Home App\lor Siri] as homeapp
}
node "FAAC-E124\lControl Unit" as e124
node "Gate" as gate

package "Home Network" as home {
  node "home hub\l(e.g. Apple TV)" as home_hub #white
  node "Raspberry Pi" as pi #white {
    [Homebridge\lService] as homebridge
  }
  node "Raspberry Pi Zero" as pi_zero #white {
    [gatecontrol\lweb service] as gatecontrol
  }
}

cloud "iCloud" {
  [HomeKit Service] as homekit_service
}

user -right-> homeapp
homeapp <-right-> homekit_service
homekit_service <--> home_hub
home_hub <--> homebridge
homebridge <-right-> gatecontrol
gatecontrol <--> e124: interfaces with
e124 <-right-> gate: controls

@enduml